<a href="https://colab.research.google.com/github/vinosraj/codingdojo-exercise/blob/main/Numpy_exercise2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
#$2 for brownie, $1 for cookie $10 for a cake
price = [2,1,10]
 
#sold for above
quantity_sold = [17,40,1]

import numpy as np

price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)

type(price_array)

print(price_array * quantity_sold_array)

#cost to make Brownie, Cookie and Cake
cost_array = np.array([0.25,0.50,5.00]) 

profit_array = price_array - cost_array

print(profit_array) 

#adding cost of pie $7 to price of items
price_array = np.append(price_array,7)
print(price_array)

# adding fudge = $4.50, Cupcake =$3 , Banana bread =$4  Torte = $9
price_array = np.append(price_array, [4.50,3,4,9])


#delete price of torte from array

price_array = np.delete(price_array,-1)

#change price of cake from 10 to 12
price_array[2] = 12

print(price_array)

#Update the  quantity_sold_array to include the sale of 2 pies,  3 trays of fudge, 16 cupcakes, and 5 loaves of banana bread. 
quantity_sold_array = np.append(quantity_sold_array, [2,3,16,5])


# Cookie change  edit the quantity_sold_array from 40 to 39.  
quantity_sold_array[1]=39
print(quantity_sold_array)

#Determine the amount of money collected from the sale of each item at the bake sale.  
print(price_array * quantity_sold_array)

amount_money_collected_array =(price_array * quantity_sold_array)
print(amount_money_collected_array)
print(np.sum(amount_money_collected_array))

#a NumPy array "quantity_leftover" that includes the quantity of 
#each item remaining at the end of the sale: 2 cakes, 1 pie, 6 trays of fudge, 2 loaves of banana bread
#brownie,cookie,cake,pie,fudge, cupcake, banana bread
quantity_leftover_array = np.array([0,0,2,1,6,0,2])
print(quantity_leftover_array)

#sell the leftover items at half price 
clearance_price_array = price_array /2

print(price_array)
print(clearance_price_array)

clearance_sale_array = quantity_leftover_array * clearance_price_array

print(clearance_sale_array)

#total sale from bake sale 
print(np.sum(clearance_sale_array)+np.sum(amount_money_collected_array))



[34 40 10]
[1.75 0.5  5.  ]
[ 2  1 10  7]
[ 2.   1.  12.   7.   4.5  3.   4. ]
[17 39  1  2  3 16  5]
[34.  39.  12.  14.  13.5 48.  20. ]
[34.  39.  12.  14.  13.5 48.  20. ]
180.5
[0 0 2 1 6 0 2]
[ 2.   1.  12.   7.   4.5  3.   4. ]
[1.   0.5  6.   3.5  2.25 1.5  2.  ]
[ 0.   0.  12.   3.5 13.5  0.   4. ]
213.5
